version: "3.3"

services:
  nginx:
    build:
      context: ./app
      dockerfile: ../nginx/Dockerfile
    container_name: reka_nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/var/www/html/app
      - ./.env:/var/www/html/app/.env
    depends_on:
      - app

  app:
    build:
      context: ./app
    container_name: reka_app
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html/app
      - ./.env:/var/www/html/app/.env
      - ./run.sh:/tmp/run.sh
    depends_on:
      - db

  db:
    image: library/mariadb:latest
    container_name: reka_db
    restart: unless-stopped
    environment:
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: